version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=nickfury'
      - 'POSTGRES_DB=tripsservice'

  app:
    build: ./
    depends_on:
      - postgres
    container_name: 'java-app'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tripsservice
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nickfury
