create table traffic_order
(
    id  bigint generated by default as identity primary key,
    car_id bigint,
    user_id bigint,
    activation_time timestamp,
    completion_time timestamp,
    status varchar(100) not null,
    status_paid varchar(100) not null,
    tariff double precision,
    balance double precision
);

create table track
(
    id bigint generated by default as identity primary key,
    order_id  bigint not null references traffic_order,
    latitude  double precision not null,
    longitude double precision not null,
    speed integer default 0,
    timestamp timestamp,
    distance  double precision default 0
);

create table images
(
    id bigint generated by default as identity primary key,
    order_id bigint not null references traffic_order,
    image varchar
);